# Usar una imagen base de Java
FROM maven:3.9.5-eclipse-temurin-17 AS builder

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Exponer el puerto en el que tu aplicación correrá
EXPOSE 8080